## Numpy Introduction

In [27]:
import numpy as np

In [28]:
height = [5.2,5.3,5.6,5.7]

In [29]:
np_height = np.array(height)
np_height

array([5.2, 5.3, 5.6, 5.7])

In [30]:
weight = [ 65.4, 59.2, 63.6, 88.4]

In [31]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4])

.

## Vector Operation:: Element-wise operation

In [12]:
bmi = np_weight / (np_height ** 2)

bmi

array([2.41863905, 2.10751157, 2.02806122, 2.72083718])

.

## Numpy arrays contain only one type unlike python inbuilt datastructure-list

In [13]:
list_in_python = [1.9,'is', True]

In [14]:
type(list_in_python[1])

str

In [15]:
numpy_test_array = np.array(list_in_python)
numpy_test_array

array(['1.9', 'is', 'True'], dtype='<U32')

In [16]:
type(numpy_test_array[0])

numpy.str_

.

## Different Types have different behaviour in python - Numpy do Vector Operations

In [17]:
height

[5.2, 5.3, 5.6, 5.7]

In [18]:
np_height

array([5.2, 5.3, 5.6, 5.7])

In [19]:
height + height

[5.2, 5.3, 5.6, 5.7, 5.2, 5.3, 5.6, 5.7]

In [20]:
np_height + np_height

array([10.4, 10.6, 11.2, 11.4])

.

## Sub-setting - to filter results based on some expression

In [21]:
print(bmi)

[2.41863905 2.10751157 2.02806122 2.72083718]


In [22]:
print(bmi[1])

2.1075115699537204


In [23]:
print(bmi>2.4)

[ True False False  True]


In [24]:
print(bmi[bmi>2.4])

[2.41863905 2.72083718]
