## Numpy Introduction

In [27]:
import numpy as np

In [28]:
height = [5.2,5.3,5.6,5.7]

In [29]:
np_height = np.array(height)
np_height

array([5.2, 5.3, 5.6, 5.7])

In [30]:
weight = [ 65.4, 59.2, 63.6, 88.4]

In [31]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4])

.

## Vector Operation:: Element-wise operation

In [12]:
bmi = np_weight / (np_height ** 2)

bmi

array([2.41863905, 2.10751157, 2.02806122, 2.72083718])

.

## Numpy arrays contain only one type unlike python inbuilt datastructure-list

In [13]:
list_in_python = [1.9,'is', True]

In [14]:
type(list_in_python[1])

str

In [15]:
numpy_test_array = np.array(list_in_python)
numpy_test_array

array(['1.9', 'is', 'True'], dtype='<U32')

In [16]:
type(numpy_test_array[0])

numpy.str_

.

## Different Types have different behaviour in python - Numpy do Vector Operations

In [17]:
height

[5.2, 5.3, 5.6, 5.7]

In [18]:
np_height

array([5.2, 5.3, 5.6, 5.7])

In [19]:
height + height

[5.2, 5.3, 5.6, 5.7, 5.2, 5.3, 5.6, 5.7]

In [20]:
np_height + np_height

array([10.4, 10.6, 11.2, 11.4])

.

## Sub-setting - to filter results based on some expression

In [21]:
print(bmi)

[2.41863905 2.10751157 2.02806122 2.72083718]


In [22]:
print(bmi[1])

2.1075115699537204


In [23]:
print(bmi>2.4)

[ True False False  True]


In [24]:
print(bmi[bmi>2.4])

[2.41863905 2.72083718]


In [1]:
import numpy as np

list_of_numbers = [1,10,100,1000,10000,100000] # or pd.Series would also work here

print(np.log(list_of_numbers)) # natural base

print(np.log10(list_of_numbers)) # base 10

print(np.log2(list_of_numbers)) # base 2

[  0.           2.30258509   4.60517019   6.90775528   9.21034037
  11.51292546]
[ 0.  1.  2.  3.  4.  5.]
[  0.           3.32192809   6.64385619   9.96578428  13.28771238
  16.60964047]


In [2]:
np.random.permutation([1,2,3,4,5,6,7,8])


array([6, 2, 5, 7, 4, 8, 3, 1])